name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: go mod
        run: |
          go mod tidy && git diff --exit-code
          go mod download
          go mod verify

      - name: gofmt
        run: gofmt -d -s .
  
      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -version -test ./...

      - name: go build
        run: |
          GOOS=linux GOARCH=arm go build -o yamn-linux-arm
          GOOS=linux GOARCH=amd64 go build -o yamn-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o yamn-windows-amd64.exe

      - name: go test
        run: go test -v -race -shuffle=on

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: yamn
          path: |
            yamn-linux-arm
            yamn-linux-amd64
            yamn-windows-amd64.exe

      - name: Copy LICENSE
        run: |
          cp $(go env GOMODCACHE)/github.com/crooks/jlog@*/LICENSE LICENSE-crooks-jlog

      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        # TODO:  
        with:
          files: |
            yamn-linux-arm
            yamn-linux-amd64
            yamn-windows-amd64.exe
            LICENSE
            LICENSE-crooks-jlog
